language: elixir
elixir: 1.3.3
otp_release:
  - 19.0
script:
  - MIX_ENV=test mix test --trace
  - MIX_ENV=test mix credo --strict
after_success:
  - mix do compile, coveralls.travis
after_script:
  - MIX_ENV=docs mix deps.get
